#MHC-GENO-final
#Before we start creat a list with the name of the samples (not to be confused with the names of the files)
#If you refer to the READ.ME example, the name of the sample is "S188_A._pigra"
#We will call this list samples_id.txt



#First we create empty lists:	(lista_leer_archivos) For reading the different files, 
#                       		(primera_fila)stores the first line of the fasta file starting with > and that contains the info
#                      			(primera_fila_total) stores all the first lines of the file the code is reading
#                       		(num_seq) stores the value of the total number of sequences in the current read file
#                       		(num_freq) stores the number of times the sequences appear in total in the current read file
#                       		(num_per) storse the percentage representation of the given sequence
#                       		(num_bp) stores the length of the each sequence


#MHC-GENO-final, code:

samples_id<-read.table("samples_id.txt", quote = "", sep = "\t", row.names = NULL, header = FALSE, stringsAsFactors=FALSE)
lista_archivos_dqa<-list.files(pattern="^seqdrb")
lista_leer_archivos<-list()
primera_fila<-list()
primera_fila_total<-list()
num_seq<-list()
num_freq<-list()
num_per<-list()
num_bp<-list()

for (ii in 1:96) {
  lista_leer_archivos[[ii]]<-read.table(paste("seqdqa_exon2_",ii,".txt",sep=""), quote = "", sep = "\t", row.names = NULL, header = FALSE, stringsAsFactors=FALSE)
  
  for (iter1 in (1:(nrow(lista_leer_archivos[[ii]])-1))) {
    num_seq[[ii]]<-lista_leer_archivos[[ii]]$V1[2:nrow(lista_leer_archivos[[ii]])]
    num_bp[[ii]]<-nchar(num_seq[[ii]])
    num_freq[[ii]]<-lista_leer_archivos[[ii]]$V2[2:nrow(lista_leer_archivos[[ii]])]
    num_per[[ii]]<-lista_leer_archivos[[ii]]$V3[2:nrow(lista_leer_archivos[[ii]])]
    primera_fila[[iter1]]<-capture.output(cat(paste(">","seq",iter1,"_",samples_id[ii,],"_dqa_exon2 ","Number_reads=",num_freq[[ii]][iter1]," ","Total_percent=",num_per[[ii]][iter1]," ","Length(bp)=",num_bp[[ii]][iter1],sep = ""), num_seq[[ii]][iter1], sep = "\n"))
  }
  primera_fila_total[[ii]]<-primera_fila
  write.table(unlist(primera_fila_total[[ii]]),paste("finaldqa_",ii,".txt", sep = ""), sep="\\n", quote=FALSE, row.names = FALSE, col.names = FALSE)
  primera_fila<-list()
}

#A nested loop is necessary to first go through each file and from that file access all the different sequences
#and values associated with each sequence within the each file
#Line19: reads the list with the names of the different samples, here we used the pattern "seqdrb"
#		 which is how we named files in MHC-GENO-stats
#Line20-27: Creating empty lists that were previously describes
#Line29: The value of "ii  is 1 to 96, as this is the number of total samples that we have as an example.
#		 This should be changed accordingly
#Line30: Reads all the files that the code will iterate through. We use the for loop to easily access
#		 all 96 files that have been previously generated by MHC-GENO-stats and have been named with
#		 a pattern that is easily accesible through regular expressions.
#Line32: Starts the nested loop. The value of "iter1" is the number of rows of the file (sequences)
#		 minus one to exclude the header.
#Line33: Retrieves each sequence from the file
#Line34: Retrieves the length of the sequences in bp
#Line35: Collects the number of times a sequences appear in total
#Line36: Compares the total number of sequences to the time a unique sequence appear to give the frequency
#		 of that unique sequence in a decimal value
#Line37: Collects all the information previously gather for each of the unique sequences and 
#		 prints it on a line above the sequence itself (Refer to READ.ME for output example)
#Line40: Writes out each final output file per sample.
